### ISSUE TITLE
Alias option of the connection string not working.

### ISSUE THREAD

**Issue by jmbertoncelli** [versae/ipython-cypher#11]
Hello,

I did try to use the alias option of the connection string without success.

when : 
%%cypher http://uuuu:pppp@localhost:7474 as c1
then:
Neo.ClientError.Statement.SyntaxError:
Invalid input 'a': expected <init> (line 1, column 1 (offset: 0))
"as c1"
 ^

thanks for your support and great work!

JM

**Comment by versae** [comment]
And you are absolutely right. No `as` treatment is done at this moment, therefore aliases never worked. I probably got carried away by the first release while writing the documentation and never really got to implement it.

**Comment by versae** [comment]
You are absolutely right. The handling of aliases is poorly implemented. I've put together a PR, once I'm able to test it I'll go ahead and merge. If by any chance you were able to review it or test it, taht'd be awesome too. At some point it would be nice to have a test suite I guess. Thanks for reporting!
