### ISSUE TITLE
Error with get_graph() and networkx 2.0

### ISSUE THREAD

**Issue by dvillaj** [versae/ipython-cypher#13]
I have found and error calling the function get_graph() with the latest version of ipython-cypher and networkx

The following notebook shows the error:

```python
!pip install -U ipython-cypher==0.2.5
```

    Collecting ipython-cypher==0.2.5
    Collecting neo4jrestclient>=2.1.0 (from ipython-cypher==0.2.5)
    Collecting ipython>=1.0 (from ipython-cypher==0.2.5)
      Using cached ipython-6.2.1-py3-none-any.whl
    Collecting prettytable (from ipython-cypher==0.2.5)
    Collecting requests>=2.1.0 (from neo4jrestclient>=2.1.0->ipython-cypher==0.2.5)
      Using cached requests-2.18.4-py2.py3-none-any.whl
    Collecting decorator (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached decorator-4.2.1-py2.py3-none-any.whl
    Collecting traitlets>=4.2 (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached traitlets-4.3.2-py2.py3-none-any.whl
    Collecting pygments (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached Pygments-2.2.0-py2.py3-none-any.whl
    Collecting pexpect; sys_platform != "win32" (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached pexpect-4.3.1-py2.py3-none-any.whl
    Collecting simplegeneric>0.8 (from ipython>=1.0->ipython-cypher==0.2.5)
    Collecting jedi>=0.10 (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached jedi-0.11.1-py2.py3-none-any.whl
    Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached prompt_toolkit-1.0.15-py3-none-any.whl
    Collecting setuptools>=18.5 (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached setuptools-38.4.0-py2.py3-none-any.whl
    Collecting pickleshare (from ipython>=1.0->ipython-cypher==0.2.5)
      Using cached pickleshare-0.7.4-py2.py3-none-any.whl
    Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.1.0->neo4jrestclient>=2.1.0->ipython-cypher==0.2.5)
      Using cached chardet-3.0.4-py2.py3-none-any.whl
    Collecting idna<2.7,>=2.5 (from requests>=2.1.0->neo4jrestclient>=2.1.0->ipython-cypher==0.2.5)
      Using cached idna-2.6-py2.py3-none-any.whl
    Collecting urllib3<1.23,>=1.21.1 (from requests>=2.1.0->neo4jrestclient>=2.1.0->ipython-cypher==0.2.5)
      Using cached urllib3-1.22-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests>=2.1.0->neo4jrestclient>=2.1.0->ipython-cypher==0.2.5)
      Using cached certifi-2017.11.5-py2.py3-none-any.whl
    Collecting ipython-genutils (from traitlets>=4.2->ipython>=1.0->ipython-cypher==0.2.5)
      Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
    Collecting six (from traitlets>=4.2->ipython>=1.0->ipython-cypher==0.2.5)
      Using cached six-1.11.0-py2.py3-none-any.whl
    Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=1.0->ipython-cypher==0.2.5)
      Using cached ptyprocess-0.5.2-py2.py3-none-any.whl
    Collecting parso==0.1.1 (from jedi>=0.10->ipython>=1.0->ipython-cypher==0.2.5)
      Using cached parso-0.1.1-py2.py3-none-any.whl
    Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=1.0->ipython-cypher==0.2.5)
      Using cached wcwidth-0.1.7-py2.py3-none-any.whl
    Installing collected packages: chardet, idna, urllib3, certifi, requests, neo4jrestclient, decorator, ipython-genutils, six, traitlets, pygments, ptyprocess, pexpect, simplegeneric, parso, jedi, wcwidth, prompt-toolkit, setuptools, pickleshare, ipython, prettytable, ipython-cypher
    Successfully installed certifi-2017.11.5 chardet-3.0.4 decorator-4.2.1 idna-2.6 ipython-6.2.1 ipython-cypher-0.2.5 ipython-genutils-0.2.0 jedi-0.11.1 neo4jrestclient-2.1.1 parso-0.1.1 pexpect-4.3.1 pickleshare-0.7.4 prettytable-0.7.2 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pygments-2.2.0 requests-2.18.4 setuptools-38.4.0 simplegeneric-0.8.1 six-1.11.0 traitlets-4.3.2 urllib3-1.22 wcwidth-0.1.7
    [33mYou are using pip version 8.1.1, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.[0m

```python
%load_ext version_information
```

```python
%load_ext cypher
```

```python
%version_information networkx, cypher
```

<table><tr><th>Software</th><th>Version</th></tr><tr><td>Python</td><td>3.5.2 64bit [GCC 5.4.0 20160609]</td></tr><tr><td>IPython</td><td>6.2.1</td></tr><tr><td>OS</td><td>Linux 4.4.0 62 generic x86_64 with Ubuntu 16.04 xenial</td></tr><tr><td>networkx</td><td>2.0</td></tr><tr><td>cypher</td><td>The 'cypher' distribution was not found and is required by the application</td></tr><tr><td colspan='2'>Tue Jan 16 16:20:12 2018 CET</td></tr></table>

```python
from py2neo import Graph
graph = Graph()
graph.delete_all()
```

```python
%cypher CREATE CONSTRAINT ON (c:Character) ASSERT c.name IS UNIQUE;
```

    0 rows affected.

<table>
    <tr>
    </tr>
</table>

```python
%%cypher 

LOAD CSV WITH HEADERS FROM "https://www.macalester.edu/~abeverid/data/stormofswords.csv" AS row
MERGE (src:Character {name: row.Source})
MERGE (tgt:Character {name: row.Target})
MERGE (src)-[r:INTERACTS]->(tgt)
ON CREATE SET r.weight = toInt(row.Weight)
```

    352 relationships created.
    107 labels added.
    459 properties set.
    107 nodes created.

<table>
    <tr>
    </tr>
</table>

```python
results = %cypher MATCH p=(:Character)-[:INTERACTS]-(:Character) RETURN p
```

    704 rows affected.

```python
g = results.get_graph()
```

    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-9-f54f19835208> in <module>()
    ----> 1 g = results.get_graph()
    

    ~/.local/lib/python3.5/site-packages/cypher/run.py in get_graph(self, directed)
        202                 properties = copy.deepcopy(node['properties'])
        203                 properties['labels'] = node['labels']
    --> 204                 graph.add_node(node['id'], properties)
        205             for rel in item['relationships']:
        206                 properties = copy.deepcopy(rel['properties'])

    TypeError: add_node() takes 2 positional arguments but 3 were given

**Comment by arfenarf** [comment]
I'm also getting this error after a very simple query.


Software | Version
-- | --
Python | 3.6.3 64bit [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
IPython | 5.1.0
OS | Darwin 16.7.0 x86_64 i386 64bit
networkx | 2.0
cypher | The 'cypher' distribution was not found and is required by the application
Thu Jan 18 09:48:12 2018 EST

```

results = %cypher http://user:password@localhost:7474/db/data MATCH p = (:Person)-[:LIKES]->(:Drink) RETURN p
results.get_graph()
```

```​
3 rows affected.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-b77a2cca2068> in <module>()
      1 results = get_ipython().magic('cypher http://neo4j:directories@localhost:7474/db/data MATCH p = (:Person)-[:LIKES]->(:Drink) RETURN p')
----> 2 results.get_graph()

/Users/kgweber/anaconda3/lib/python3.6/site-packages/cypher/run.py in get_graph(self, directed)
    202                 properties = copy.deepcopy(node['properties'])
    203                 properties['labels'] = node['labels']
--> 204                 graph.add_node(node['id'], properties)
    205             for rel in item['relationships']:
    206                 properties = copy.deepcopy(rel['properties'])

TypeError: add_node() takes 2 positional arguments but 3 were given
```

**Comment by versae** [comment]
It seems to be an artifact of the latest merge. I really need tests! Thanks for reporting, I'll get it fixed as soon as I can.

**Comment by anupamtiwari05** [comment]
I am also getting the same error: add_node() takes 2 positional arguments but 3 were given

Please have a look at the attached screenshot.

![image](https://user-images.githubusercontent.com/30790045/37563735-de43d316-2a5d-11e8-8108-9b967f252873.png)

Please help me with the solution or advise if I am doing anything wrong here. Thank you.

**Comment by OscarSouth** [comment]
I'm having trouble with this problem today when trying to import through ipython-cypher:

Input:
```
%config CypherMagic.auto_networkx = True
testdf = %cypher MATCH (a)-[]->(b) RETURN a, b LIMIT 15
```

Result:
```
~/anaconda3/lib/python3.6/site-packages/cypher/run.py in get_graph(self, directed)
    200             for node in item['nodes']:
    201                 graph.add_node(node['id'], node['properties'],
--> 202                                labels=node['labels'])
    203             for rel in item['relationships']:
    204                 graph.add_edge(rel['startNode'], rel['endNode'], rel['id'],

TypeError: add_node() takes 2 positional arguments but 3 were given
```

**Comment by versae** [comment]
Hopefully it's fixed now. I run:
```
$ docker run -p "7474:7474" -p "7687:7687" -e "NEO4J_AUTH=none" --volume=$HOME/neo4j/data:/data neo4j
```
And then tested it in the notebooks [examples](https://github.com/versae/ipython-cypher/blob/master/docs/examples.ipynb) and [test](https://github.com/versae/ipython-cypher/blob/master/docs/test.ipynb).

Released the new version at [PyPI](https://pypi.org/project/ipython-cypher/).

**Comment by versae** [comment]
@anupamtiwari05, I'm sorry, but it is not clear to me how is that an issue with `ipython-cypher`. It seems like in the newer versions of NetworkX you would beed to do something like
```python
G.add_node('Anu', name='Anu', age=30)
```
Cheers.

**Comment by jbaktir** [comment]
I have fixed this by specifying the arguments in the source code.

Go ahead and find the "run.py" file in "~/anaconda3/lib/python3.6/site-packages/cypher/run.py" and change the corresponding section to this:
```
        for item in self._results.graph:
            for node in item['nodes']:
                graph.add_node(node['id'], attr_dict=node['properties'],labels=node['labels'])
            for rel in item['relationships']:
                graph.add_edge(rel['startNode'], rel['endNode'], key=rel['id'], attr_dict=rel['properties'],type=rel['type'])
```
