### ISSUE TITLE
draw and get_graph appear to be broken

### ISSUE THREAD

**Issue by dkoslicki** [versae/ipython-cypher#9]
Using the neo4j example data (Movie Graph), I get the following error:
```python
res = cypher.run("match (n)-[r]-() return n, r")  # as per the documentation
res.get_graph()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/<snip>/lib/python3.5/site-packages/cypher/run.py", line 202, in get_graph
    labels=node['labels'])
TypeError: add_node() takes 2 positional arguments but 3 were given
```
similarly:
```python
res = cypher.run("match (n)-[r]-() return n, r")  # as per the documentation
res.draw()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/<snip>/lib/python3.5/site-packages/cypher/run.py", line 268, in draw
    graph = self.get_graph(directed=directed)
  File "/home/<snip>/lib/python3.5/site-packages/cypher/run.py", line 202, in get_graph
    labels=node['labels'])
TypeError: add_node() takes 2 positional arguments but 3 were given
```
Perhaps [line 201-202](https://github.com/versae/ipython-cypher/blob/master/src/cypher/run.py#L201-L202) in ``run.py`` could be replaced with:
```python
graph.add_node(node['id'], properties=node['properties'], labels=node['labels'])
```

**Comment by dkoslicki** [comment]
Oh yeah, and same for [the following lines](https://github.com/versae/ipython-cypher/blob/master/src/cypher/run.py#L204-L205).

**Comment by dkoslicki** [comment]
I also realize it's been a year since this project was updated, so if you want to direct me to a better "neo4j to networkx" converter instead of fixing, feel free to.

**Comment by versae** [comment]
Thanks for commenting! It's true I don't have more time to devote to this but if you send a PR I'll review and merge.

**Comment by versae** [comment]
Should be fixed now thanks to @arjoe 👍

**Comment by dkoslicki** [comment]
Awesome! Thanks!
